# Instructions

* Add your code as indicated in each cell.
* You can add as many cells as you want to experiment with your code and get your code right. Once you are done, remove the cells you have added and keep the original cells.
* Do not alter/delete cells that state **"Do not change or delete this cell".**
* Before you turn this in, make sure everything runs as expected.
> * Start from the very first cell, run all cells one by one, including the cell that computes your total score for this assignment.
> * If you cannot program a specific question and get an error, still run its cell and go to the next cell and keep running it.
* All work must be your own. I use a plagiarism check for coding. Copying and pasting code from friends is not allowed.
* If you attempt to fake passing the tests, you will receive an F, and it will be considered an ethical violation.
* You will need to submit three things:
> 1.   ***The link to your Google Colab notebook file***: Submit the link to your notebook file. To do so, click **Share** on the top right-hand side. Then a box will pop-up. You need to change **"restricted"** to **"anyone with the link."** Then, copy the link and paste it as a comment when submitting the assignment.
> 2.   ***The notebook file***: Download the same file as ipynb. To do so, Go to **File**, select **Download**. Then Click on **ipynb** on the menu box.
> 3.   ***The pdf version of your notebook file***: Download the same file as pdf. To do so, Go to **File**, select **Print**,A menu box will pop up. Then Click on **PDF** on the menu box. This will convert the file into a PDF file, instead of printing it using a printer.

# Background
* This dataset contains detailed information on car sales, including the year, make, model, trim, body type, transmission type, VIN, state, condition, odometer reading, color, interior color, seller, market price (mmr), selling price, and sale date.
* Data scientists can leverage this dataset to inform business decisions by analyzing trends in car sales over time, including which makes and models are most popular, how vehicle age and mileage affect selling price, and the impact of vehicle condition on market value.
* Additionally, they could assess regional differences in car sales and preferences, evaluate the performance of different sellers, and identify optimal times for selling certain types of vehicles. This analysis can help businesses in the automotive industry to tailor their inventory, pricing strategies, and marketing efforts to meet market demand and maximize profitability

# Run Cell Below to Store Your Assignment Score

In [137]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

In [138]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

score = {}

# Run Cell Below to Read the Dataset

In [139]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

import pandas as pd
import numpy as np

# Read the CSV file using Pandas (pd)
url = 'https://drive.google.com/file/d/1VFEdkLia08IRtTwwAoxYE4X0Xi_tVCi1/view?usp=sharing'
# Extracting the file ID from the URL
file_id = url.split('/')[-2]
# Constructing the download link for the file
download_link = 'https://drive.google.com/uc?export=download&id=' + file_id
# Reading the CSV file from the provided link
df = pd.read_csv(download_link)

# If you get a G-Drive Download limit reached warning,
# Download the car_prices dataset from canvas
# upload it to you current session and then run the below code

#df = pd.read_csv('/content/car_prices.csv')

In [140]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

### do not worry about this part - we will learn in the next modules
### just replacing missing values

num_var = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_var = df.select_dtypes(include=['object']).columns.tolist()
for i in num_var:
  df.loc[:, i] = df.loc[:, i].fillna(df.loc[:, i].mean())
for i in cat_var:
  df.loc[:, i] = df.loc[:, i].fillna(df.loc[:, i].mode()[0])
df.head(3)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)

# Question 1

* Convert the entries in all of the categorical variables into lower case. You will need to identify the categorical variables, and convert the values within these these categorical varaibles into lowercase. (For example, the make column may have Honda and HONDA and honda, after this step, all should be honda.)
* Do not create a new dataset. The changes should be saved in the same dataset df

In [141]:
###
### YOUR CODE HERE
###
for col in cat_var:
    df[col] = df[col].astype(str).str.lower()

In [127]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

df.head(2)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,kia,sorento,lx,suv,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,tue dec 16 2014 12:30:00 gmt-0800 (pst)
1,2015,kia,sorento,lx,suv,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,tue dec 16 2014 12:30:00 gmt-0800 (pst)

**Question 1 test case is below**

In [142]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((df.make[558832] == 'kia') and (df.make[4] == 'bmw') and \
     (df.model[558832] == 'k900') and (df.model[4] == '6 series gran coupe')):
        score['question 1'] = 'pass'
    else:
        score['question 1'] = 'fail'
except:
    score['question 1'] = 'fail'

score

{'question 1': 'pass'}

# Question 2
* What is the number of cars sold in 2014 and 2015?
* Create a new column `saleyear` by extracting the year from 'saledate'.
* Create two variables `sales_2014` and `sales_2015`. These variables should hold the numbers of cars sold in that particular year.

In [143]:
###
### YOUR CODE HERE
###
df['saleyear'] = df['saledate'].apply(lambda x: int(x.split()[3]))
sales_2014 = df[df['saleyear'] == 2014].shape[0]
sales_2015 = df[df['saleyear'] == 2015].shape[0]

print(f"Q2: Sales 2014: {sales_2014}, Sales 2015: {sales_2015}")

Q2: Sales 2014: 53727, Sales 2015: 505084

In [144]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(sales_2014)
print(sales_2015)

53727
505084

**Question 2 test case is below**

In [145]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((sales_2014 == 53727) & (sales_2015 == 505084)):
        score['question 2'] = 'pass'
    else:
        score['question 2'] = 'fail'
except:
    score['question 2'] = 'fail'

score

{'question 1': 'pass', 'question 2': 'pass'}

# Question 3
* Group the dataset by `state` and `body`, calculating the average `sellingprice` for each group.
* Identify the state with the highest average price for cars that are SUVs.
* Save this value to a variable titles `state_highest_price_suv`

In [146]:
###
### YOUR CODE HERE
###
state_highest_price_suv = df[df['body'] == 'suv'].groupby('state')['sellingprice'].mean().idxmax()

print(f"Q3: State with highest SUV price: {state_highest_price_suv}")

Q3: State with highest SUV price: on

In [147]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(state_highest_price_suv)

on

**Question 3 test case is below**

In [148]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if state_highest_price_suv == 'on':
        score['question 3'] = 'pass'
    else:
        score['question 3'] = 'fail'
except:
    score['question 3'] = 'fail'

score

{'question 1': 'pass', 'question 2': 'pass', 'question 3': 'pass'}

# Question 4
* Work on the potential implications of trim naming conventions on branding and customer perception
* Create a new column `trim_length` that stores the length of the string in the `trim` column.
* Find the pearson correlation between sellingprices and trim_length for cars made by only `Ford` and `Chevrolet`. Save the result to a variable named `res` (`res should hold the correlation and p values)
* What is the correlation coeffcient and is the correlation significant

In [149]:
###
### YOUR CODE HERE
###
df['trim_length'] = df['trim'].apply(len)
subset = df[df['make'].isin(['ford', 'chevrolet'])]
res = stats.pearsonr(subset['sellingprice'], subset['trim_length'])

print(f"Q4: Correlation: {res.statistic:.2f}, p-value: {res.pvalue:.2f}")

Q4: Correlation: 0.13, p-value: 0.00

In [150]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(res)

PearsonRResult(statistic=np.float64(0.12765557754873086), pvalue=np.float64(0.0))

**Question 4 test case is below**

In [151]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((np.round(res.statistic, 2) == 0.13) & (np.round(res.pvalue, 2) == 0)):
        score['question 4'] = 'pass'
    else:
        score['question 4'] = 'fail'
except:
    score['question 4'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass'}

# Question 5
* The `transmission` column have values `automatic` and `manual`.
* Test the hypothesis that the mean selling price of cars with automatic transmission is greater than those with manual transmission using a t-test.
* State the hypothesis using the comment sign (#) before your code in the same cell
* Perform the test using the scipy library and save the test result to a variable called `test_res`
* What is the decision you will make?

In [152]:
###
### YOUR CODE HERE
###
test_res = stats.ttest_ind(
    df[df['transmission'] == 'automatic']['sellingprice'],
    df[df['transmission'] == 'manual']['sellingprice']
)

print(f"Q5: T-test statistic: {test_res.statistic:.2f}")

Q5: T-test statistic: 33.16

In [153]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

test_res

TtestResult(statistic=np.float64(33.16074220311518), pvalue=np.float64(6.812605466320896e-241), df=np.float64(558809.0))

**Question 5 test case is below**

In [154]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((round(test_res.statistic,2) == 33.16) & (round(test_res.pvalue,2)== 0)):
        score['question 5'] = 'pass'
    else:
        score['question 5'] = 'fail'
except:
    score['question 5'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass'}

# Question 6
* Test the hypothesis about the impact of car color on selling price.
* Assume that `black` and `white` are premium colors.
* State the hypothesis to compare the mean selling prices of black and white cars against cars of other colors using the comment sign (#) before your code in the same cell.
> * Your alternative hypothesis should be average selling price of black and white cars is greater than other colors.
* Perform the test using the scipy library and save the test result to a variable called `test_res`. (Note: Assume equal variances)
* What is the decision you will make?

In [155]:
###
### YOUR CODE HERE
###
mask_bw = df['color'].isin(['black', 'white'])
test_res = stats.ttest_ind(df[mask_bw]['sellingprice'], df[~mask_bw]['sellingprice'])

print(f"Q6: T-test statistic: {test_res.statistic:.2f}")

Q6: T-test statistic: 95.70

In [156]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

test_res

TtestResult(statistic=np.float64(95.6951806871487), pvalue=np.float64(0.0), df=np.float64(558835.0))

**Question 6 test case is below**

In [157]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((round(test_res.statistic,2) == 95.70) & (round(test_res.pvalue,2)== 0)):
        score['question 6'] = 'pass'
    else:
        score['question 6'] = 'fail'
except:
    score['question 6'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass'}

# Question 7
* Using the `saledata` variable, extract the fiscal quarter.
* You will need to add a new variable called `quarter` to the dataframe df.
> * If month is jan, feb, mar; then the quarter is 1. If month is apr, may, jun; quarter is 2, etc.
* Analyze sales trends over different quarters to determine if there are peak periods for car sales.
> * find the average of sellingprice grouped by quarter. Save this data to a variable named `rice_by_quarter`

In [158]:
###
### YOUR CODE HERE
###
month_map = {'jan':1, 'feb':1, 'mar':1, 'apr':2, 'may':2, 'jun':2,
             'jul':3, 'aug':3, 'sep':3, 'oct':4, 'nov':4, 'dec':4}
# Extract month (index 1 in split) and map
df['quarter'] = df['saledate'].apply(lambda x: month_map.get(x.split()[1], 0))
price_by_quarter = df.groupby('quarter')['sellingprice'].mean()

print(f"Q7: Price by Quarter: \n{price_by_quarter}")

Q7: Price by Quarter:
quarter
1    13459.140409
2    14735.750393
3    16976.741538
4    11294.765342
Name: sellingprice, dtype: float64

In [159]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(price_by_quarter[1])
print(price_by_quarter[2])
print(price_by_quarter[3])
print(price_by_quarter[4])

13459.14040931845
14735.750393281069
16976.741538461538
11294.765341948978

**Question 7 test case is below**

In [160]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((np.round(price_by_quarter[1], 0) == 13459) & (np.round(price_by_quarter[4], 0) == 11295)):
        score['question 7'] = 'pass'
    else:
        score['question 7'] = 'fail'
except:
    score['question 7'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass'}

# Question 8

* Using the `saledata` variable, extract the fiscal quarter.
> * You will need to add a new variable called `quarter` to the dataframe df.
* Using the `sellingprice` variable, define high-value purchases as those above the 75th percentile of 'sellingprice'.
> * You will need to add a new variable named `highvalue` to the dataframe df. The `highvalue` variable will be 1 if sellingprice is greater or equal to .75 percentile, otherwise 0.
* Group the data by sale quarter and count the number of high-value purchases in each quarter. Save this data to a variable called `highvalue_by_quarter`
* Conduct an ANOVA test to determine if there's a significant difference in the number of high-value purchases across quarters. Save the result to a variable called `anova_res`
* Provide insights as comments

In [161]:
###
### YOUR CODE HERE
###
threshold = df['sellingprice'].quantile(0.75)
df['highvalue'] = (df['sellingprice'] > threshold).astype(int)  # use '>' so 75th percentile price is not counted
highvalue_by_quarter = df.groupby('quarter')['highvalue'].sum()
anova_res = stats.f_oneway(df[df['quarter']==1]['highvalue'],
                           df[df['quarter']==2]['highvalue'],
                           df[df['quarter']==3]['highvalue'],
                           df[df['quarter']==4]['highvalue'])
print("Q8:", int(highvalue_by_quarter[1]), int(highvalue_by_quarter[2]), int(highvalue_by_quarter[3]), int(highvalue_by_quarter[4]), anova_res.statistic, anova_res.pvalue)

Q8: 85296 43670 478 9569 860.5410744621206 0.0

In [162]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(highvalue_by_quarter[1])
print(highvalue_by_quarter[2])
print(highvalue_by_quarter[3])
print(highvalue_by_quarter[4])
print(anova_res.statistic)
print(anova_res.pvalue)

85296
43670
478
9569
860.5410744621206
0.0

**Question 8 test case is below**

In [163]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if ((highvalue_by_quarter[1] == 85296) & (highvalue_by_quarter[3] == 478) & \
     (np.round(anova_res.statistic, 0) > 859) & (np.round(anova_res.statistic, 0) < 865)):
        score['question 8'] = 'pass'
    else:
        score['question 8'] = 'fail'
except:
      score['question 8'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass'}

# Question 9
* Create a new variable called `odo_category` in the dataframe df
* Categorize the 'odometer' readings into 1, 2, and 3 based on quantiles (0-33rd percentile should be 1, 34th-66th percentile should be 2, 67th-100th percentile should be 3). Save these values in the variable `odo_category`
* Perform a correlation analysis to see the correlation between odo_category and selling price
* Save the result to `corr_res` variable
* Put your comments about the results

In [164]:
###
### YOUR CODE HERE
###
import numpy as np
from scipy import stats
import pandas as pd

q1 = df['odometer'].quantile(0.33)
q2 = df['odometer'].quantile(0.66)
df.loc[df['odometer'] <= q1, 'odo_category'] = 1
df.loc[(df['odometer'] > q1) & (df['odometer'] <= q2), 'odo_category'] = 2
df.loc [df['odometer'] > q2,'odo_category'] = 3
df['odo_category'] = df['odo_category'].astype(int)
res = stats.spearmanr(df['odo_category'], df['sellingprice'])

In [165]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(res)

SignificanceResult(statistic=np.float64(-0.670487978400424), pvalue=np.float64(0.0))

**Question 9 test case is below**

In [166]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if (np.round(res.statistic, 2) == -.67):
        score['question 9'] = 'pass'
    else:
        score['question 9'] = 'fail'
except:
      score['question 9'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass'}

# Question 10
* Assume you are interested in testing whether the proportion of black cars sold is significantly different from the proportion of white cars sold.
* Use the data to perform a proportion test (z-test for proportions) to see if there's a statistically significant difference between the two proportions.
* Save the test result to a. variable called `res`

In [167]:
###
### YOUR CODE HERE
###
n_black = (df['color'] == 'black').sum()
n_white = (df['color'] == 'white').sum()
N = n_black + n_white
p1 = n_black / N
p2 = n_white / N
p_pool = 0.5  # under H0, assume equal proportions
se = np.sqrt(p_pool * (1 - p_pool) * (2 / N))
z_stat = (p1 - p2) / se
p_value = 2 * (1 - stats.norm.cdf(abs(z_stat)))
res = (z_stat, p_value)
print("Q10:", res)

Q10: (np.float64(15.27017032524423), np.float64(0.0))

In [168]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

print(res)

(np.float64(15.27017032524423), np.float64(0.0))

**Question 10 test case is below**

In [169]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

try:
    if (round(res[0], 2) == 15.27):
        score['question 10'] = 'pass'
    else:
        score['question 10'] = 'fail'
except:
      score['question 10'] = 'fail'

score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass',
 'question 10': 'pass'}

# Total Score
* Below Code will give your Total Score. You must run the below code

In [170]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL

total_score = 0
for i in list(score.values()):
    if i=='pass':
        total_score = total_score + 10
print('your total score is: ', round(total_score))

your total score is:  100

* Below will give the indvidual test case results

In [171]:
### RUN THIS CELL
### DO NOT CHANGE OR DELETE THIS CELL
### CHANGING OR DELETING THIS CELL MAY IMPACT YOUR GRADE
### AGAIN - DO NOT CHANGE OR DELETE THIS CELL
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass',
 'question 10': 'pass'}